### ISSUE TITLE
redmine_select2 plugin duplicates to Undev/redmine__select2

### ISSUE THREAD

**Issue by jcppkkk** [nanego/redmine_templates#1]
Hi @nanego 
there is another select2 plugin made by @nodecarter  https://github.com/Undev/redmine__select2

Is there any chance you replace your select2 dependence with Undev's? I would like to keep single select2 plugin in my redmine system. Please think about the possibility, thanks!

**Comment by nanego** [comment]
Hi @jcppkkk
I will give it a try.
We should not maintain both select2 plugins if they have same purposes and identical functionalities.

**Comment by nanego** [comment]
Hi
As the select2 function was only used in the plugin settings, I have make the use of a select2 plugin optional. The form will use the standard select tag if select2 is not available.
So you can now use the plugin of your choice ;)
