### ISSUE TITLE
mysqlerror

### ISSUE THREAD

**Issue by ashrafalzyoud** [nanego/redmine_templates#14]
Mysql2::Error: BLOB, TEXT, GEOMETRY or JSON column 'template_description' can't have a default value: ALTER TABLE `issue_templates` ADD `template_description` text DEFAULT '{}'
/home/redmine/4.11/plugins/redmine_templates/db/migrate/20191008151500_add_description_to_templates.rb:3:in `change'

**Comment by nanego** [comment]
Thanks for reporting the issue.
It was only happening with MySQL databases.
It has been fixed in the latest version of the plugin.
